
export var parameter = {
	show: {
		blendTree: 1.,
		blendSnow: 0.,
		blendRain: 0.,
		blendSmoke: 0.,
		blendFlash: 0.,
		blendFire: 0.,
	},
	global: {
		blendLabelAlpha: 1,
		blendLabelFire: 0,
		blendStorm: 0,
		blendLight: 0,
		blendHeat: 0,
		blendBurnOut: 0,
	},
	particle: {
		// feedbackBlend: 0.5,
		velocitySpeed: 0.04,
		velocityTargetBlend: 0.,
		velocityOriginBlend: 0.,
		velocityNoiseBlend: 0.21,
		velocityTornadoBlend: 0.,
		velocityDirectionBlend: 0.41,
		velocityFrictionBlend: 1.,
		velocityDamping: 0.05,
		spriteVelocityStretch: 3.,
		turbulenceRangeMin: 0.8,
		turbulenceRangeMax: 0.9,
	},
	particleHeat: {
		// feedbackBlend: 0.5,
		velocitySpeed: 0.325,
		velocityTargetBlend: 0.,
		velocityOriginBlend: 0.,
		velocityNoiseBlend: 0.57,
		velocityTornadoBlend: 0.19,
		velocityDirectionBlend: 0.07,
		velocityFrictionBlend: 1.,
		velocityDamping: 0.05,
		spriteVelocityStretch: 31.9,
		turbulenceRangeMin: 0.8,
		turbulenceRangeMax: 0.9,
	},
};
