export default {
	texts: [
		'Once upon a time',
		'during a cold winter',
		'the demoscene spirit was in danger.',
		'The elite sceners were all asleep.',
		'4klang had been replaced by Unity.',
		'The scene was dead.',
		'But there it came!',
		'A new hope was born,',
		'arising from the ashes of the past,',
		'the crowd gathered at',
		'Cookie\nDeMoPARTy',
		'December 8th and 9th 2017\nParis France',
		'Thankfully the beers were still cold.',
		'greets to\nLJ Raxter Flush\nResistance X-Men\nUnix Calodox\nGLKT XT95 Eybor',
		'we love\nmercury still\nasd cocoon razor1911\nhoodlum paradox\nyou',
		'credits\nartcode ponk\ncode koltes\nmusic fergus',
	],
};
