export default {
	time: { value: 1.0 },
	frameScene: { value: 0 },
	frameTunnel: { value: 0 },
	resolution: { value: [window.innerWidth, window.innerHeight] },
	sceneOpacity: { value: 0 },
	tunnelOpacity: { value: 0 },
	finalSymbol: { value: 0 },
	headRotationDelay: { value: 0 },
	headRoundness: { value: 0 },
	introSymbol: { value: 0 },
	joOffset: { value: 0 },
	ribbon: { value: 0 },
	flying: { value: 0 },
};
